name: Build Hybris base ant image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'hybris-base/ant/**'
      - '!hybris-base/ant/**.md'

env:
  IMAGE_NAME: 953612792372.dkr.ecr.eu-west-1.amazonaws.com/hybris/base

jobs:
  build:
    name: Build & push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HYBRIS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.HYBRIS_DEPLOY_SECRET }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::953612792372:role/hybris-containers-deployment
          role-duration-seconds: 1200

      - name: Login to Docker
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 953612792372.dkr.ecr.eu-west-1.amazonaws.com

      - name: Building Hybris Docker base ant image
        run: |
          docker build \
          -f hybris-base/ant/Dockerfile \
          -t ${{ env.IMAGE_NAME }}:ant-${GITHUB_SHA::8} \
          hybris-base/ant

      - name: Push Hybris Docker base ant image to ECR
        run: |
          docker push ${{ env.IMAGE_NAME }}:ant-${GITHUB_SHA::8}
