name: list current prd db snapshots
on:
  workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_SA_DB_SNAPSHOT_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SA_DB_SNAPSHOT_ACCESS_SECRET}}
          aws-region: eu-west-1

      - name: List Current Production Snapshots
        run: |
          echo "Current Optimised Production Snapshots listed below:"
          aws rds describe-db-cluster-snapshots --db-cluster-identifier aws-percona-aurora --output json | jq -r '.DBClusterSnapshots[].DBClusterSnapshotIdentifier' | grep db-optimize

      - name: Click here if you wish to create a new snapshot
        run: echo "https://github.com/matchesfashion/db-refresh/actions?query=workflow%3Acreate-prd-db-snapshot-and-optimize"

