name: Test Pipeline
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      TF_action:
        description: Test Input
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  test_echo:
    runs-on: ubuntu-latest
    steps:
      - name: Test Pipeline
        run: |
          echo "This is a test pipeline"
