name: Update Secrets

on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::853297308812:role/GitHubActionsSecretsRole
          aws-region: eu-west-2

      - name: Update secret
        run: |
          aws secretsmanager put-secret-value \
            --secret-id GithubActionsDemo \
            --secret-string 'TEST2'
