name: Update AWS Secret

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'The name of the secret in AWS Secrets Manager'
        required: true
        default: 'your-default-secret-name'
      new_secret_value:
        description: 'The new value for the secret'
        required: true
        default: 'your-default-secret-value'
      aws_region:
        description: 'The AWS region where the secret is located'
        required: true
        default: 'eu-west-2'

jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
name: Checkout code
        uses: actions/checkout@v2

name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ github.event.inputs.aws_region }}

name: Update Secret in AWS Secrets Manager
        run: |
          aws secretsmanager update-secret --secret-id ${{ github.event.inputs.secret_name }} --secret-string ${{ github.event.inputs.new_secret_value }}