name: Update AWS Secret

on:
  workflow_dispatch:
    inputs:
      aws-region:
        description: "AWS region (e.g. us-east-1)"
        required: true
        default: "eu-west-2"
      secret-id:
        description: "The AWS Secrets Manager secret ID or ARN"
        required: true
      secret-value:
        description: "The new secret value (JSON or plain text)"
        required: true

permissions:
  id-token: write   
  contents: read    

jobs:
  update-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsSecretsRole
          aws-region: ${{ github.event.inputs.aws-region }}

      - name: Update secret value in AWS Secrets Manager
        run: |
          echo "Updating secret: ${{ github.event.inputs.secret-id }}"
          aws secretsmanager put-secret-value \
            --secret-id "${{ github.event.inputs.secret-id }}" \
            --secret-string "${{ github.event.inputs.secret-value }}"
